export const ADD_PROPOSAL = 'ADD_PROPOSAL';
export const START_PROPOSAL_ADD = 'START_PROPOSAL_ADD';
export const REQUEST_PROPOSALS = 'REQUEST_PROPOSALS';
export const RECEIVE_PROPOSAL = 'RECEIVE_PROPOSAL';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const HIDE_DETAILS = 'HIDE_DETAILS';
export const OPEN_POPUP = 'OPEN_POPUP';
